language: julia
julia:
- 1.0
- nightly
matrix:
  allow_failures:
    - julia: nightly
after_success:    
- julia -e 'using Pkg; cd(Pkg.dir("EconPDEs")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
notifications:
  email: false
  on_failure: change